# Generated by Django 4.2.1 on 2023-06-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('tipo', models.CharField(max_length=15, verbose_name='TipoVeiculo')),
                ('cor', models.CharField(max_length=20, verbose_name='Cor')),
            ],
        ),
    ]
