# Generated by Django 4.2.1 on 2023-06-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_veiculo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço Custo'),
        ),
    ]
